# Generated by Django 3.0.5 on 2020-06-07 12:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='citizenships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship_code', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('citizenship_country', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='destination_country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_country_code', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('destination_country_description', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='hotspot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotspot_code', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('hotspot_location', models.CharField(max_length=20)),
                ('hotspot_capacity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
            ],
        ),
        migrations.CreateModel(
            name='marital_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status_code', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('no_of_children', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('marital_status_description', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex_code', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999)])),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_code', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('skill_description', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='refugge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('father_name', models.CharField(max_length=25)),
                ('mother_name', models.CharField(max_length=25)),
                ('date_of_birth', models.DateField()),
                ('asylum_request', models.CharField(max_length=5)),
                ('email_address', models.EmailField(max_length=30)),
                ('photo_picture', models.ImageField(upload_to='')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('citizenship_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refugee.citizenships', to_field='citizenship_code')),
                ('destination_country_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refugee.destination_country', to_field='destination_country_code')),
                ('hotspot_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refugee.hotspot', to_field='hotspot_code')),
                ('marital_status_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refugee.marital_status', to_field='marital_status_code')),
                ('sex_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refugee.sex', to_field='sex_code')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refugee.skills', to_field='skill_code')),
            ],
        ),
    ]
